steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ghost:latest', '.']
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ghost:latest']
    id: 'push-image'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ghost'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ghost:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '2368'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},GCS_BUCKET=${_GCS_BUCKET},GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,MAIL_USER=mail-user:latest,MAIL_PASSWORD=mail-password:latest,GCS_KEYFILE=gcs-keyfile:latest'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_CONNECTION_NAME}'
      - '--vpc-connector'
      - '${_VPC_CONNECTOR}'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
    id: 'deploy-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/ghost:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

substitutions:
  _DB_HOST: '127.0.0.1'  # Will be set via Cloud SQL proxy
  _DB_PORT: '3306'
  _DB_USER: 'ghost'
  _DB_NAME: 'ghost'
  _GCS_BUCKET: ''  # Set via --substitutions flag
  _CLOUDSQL_CONNECTION_NAME: ''  # Set via --substitutions flag
  _VPC_CONNECTOR: ''  # Set via --substitutions flag
  _SERVICE_ACCOUNT: ''  # Set via --substitutions flag
